
public class Graphic
{
    public static void move()
    {
        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |   0                                                |         |");
        System.out.println("|          |  -|-                                               |         |");
        System.out.println("|          |   |                                                |         |");
        System.out.println("|          |   /\\                                               |         |");
        Act.wait(20);
        
        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |    0                                               |         |");
        System.out.println("|          |   -|-                                              |         |");
        System.out.println("|          |    |                                               |         |");
        System.out.println("|          |    /\\                                              |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |     0                                              |         |");
        System.out.println("|          |    -|-                                             |         |");
        System.out.println("|          |     |                                              |         |");
        System.out.println("|          |     /\\                                             |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |      0                                             |         |");
        System.out.println("|          |     -|-                                            |         |");
        System.out.println("|          |      |                                             |         |");
        System.out.println("|          |      /\\                                            |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |       0                                            |         |");
        System.out.println("|          |      -|-                                           |         |");
        System.out.println("|          |       |                                            |         |");
        System.out.println("|          |       /\\                                           |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |        0                                           |         |");
        System.out.println("|          |       -|-                                          |         |");
        System.out.println("|          |        |                                           |         |");
        System.out.println("|          |        /\\                                          |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |         0                                          |         |");
        System.out.println("|          |        -|-                                         |         |");
        System.out.println("|          |         |                                          |         |");
        System.out.println("|          |         /\\                                         |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |          0                                         |         |");
        System.out.println("|          |         -|-                                        |         |");
        System.out.println("|          |          |                                         |         |");
        System.out.println("|          |          /\\                                        |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |           0                                        |         |");
        System.out.println("|          |          -|-                                       |         |");
        System.out.println("|          |           |                                        |         |");
        System.out.println("|          |           /\\                                       |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |            0                                       |         |");
        System.out.println("|          |           -|-                                      |         |");
        System.out.println("|          |            |                                       |         |");
        System.out.println("|          |            /\\                                      |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |             0                                      |         |");
        System.out.println("|          |            -|-                                     |         |");
        System.out.println("|          |             |                                      |         |");
        System.out.println("|          |             /\\                                     |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |              0                                     |         |");
        System.out.println("|          |             -|-                                    |         |");
        System.out.println("|          |              |                                     |         |");
        System.out.println("|          |              /\\                                    |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |               0                                    |         |");
        System.out.println("|          |              -|-                                   |         |");
        System.out.println("|          |               |                                    |         |");
        System.out.println("|          |               /\\                                   |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                0                                   |         |");
        System.out.println("|          |               -|-                                  |         |");
        System.out.println("|          |                |                                   |         |");
        System.out.println("|          |                /\\                                  |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                 0                                  |         |");
        System.out.println("|          |                -|-                                 |         |");
        System.out.println("|          |                 |                                  |         |");
        System.out.println("|          |                 /\\                                 |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                  0                                 |         |");
        System.out.println("|          |                 -|-                                |         |");
        System.out.println("|          |                  |                                 |         |");
        System.out.println("|          |                  /\\                                |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                   0                                |         |");
        System.out.println("|          |                  -|-                               |         |");
        System.out.println("|          |                   |                                |         |");
        System.out.println("|          |                   /\\                               |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                    0                               |         |");
        System.out.println("|          |                   -|-                              |         |");
        System.out.println("|          |                    |                               |         |");
        System.out.println("|          |                    /\\                              |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                     0                              |         |");
        System.out.println("|          |                    -|-                             |         |");
        System.out.println("|          |                     |                              |         |");
        System.out.println("|          |                     /\\                             |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                      0                             |         |");
        System.out.println("|          |                     -|-                            |         |");
        System.out.println("|          |                      |                             |         |");
        System.out.println("|          |                      /\\                            |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                       0                            |         |");
        System.out.println("|          |                      -|-                           |         |");
        System.out.println("|          |                       |                            |         |");
        System.out.println("|          |                       /\\                           |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                        0                           |         |");
        System.out.println("|          |                       -|-                          |         |");
        System.out.println("|          |                        |                           |         |");
        System.out.println("|          |                        /\\                          |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                         0                          |         |");
        System.out.println("|          |                        -|-                         |         |");
        System.out.println("|          |                         |                          |         |");
        System.out.println("|          |                         /\\                         |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                          0                         |         |");
        System.out.println("|          |                         -|-                        |         |");
        System.out.println("|          |                          |                         |         |");
        System.out.println("|          |                          /\\                        |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                           0                        |         |");
        System.out.println("|          |                          -|-                       |         |");
        System.out.println("|          |                           |                        |         |");
        System.out.println("|          |                           /\\                       |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                            0                       |         |");
        System.out.println("|          |                           -|-                      |         |");
        System.out.println("|          |                            |                       |         |");
        System.out.println("|          |                            /\\                      |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                             0                      |         |");
        System.out.println("|          |                            -|-                     |         |");
        System.out.println("|          |                             |                      |         |");
        System.out.println("|          |                             /\\                     |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                              0                     |         |");
        System.out.println("|          |                             -|-                    |         |");
        System.out.println("|          |                              |                     |         |");
        System.out.println("|          |                              /\\                    |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                               0                    |         |");
        System.out.println("|          |                              -|-                   |         |");
        System.out.println("|          |                               |                    |         |");
        System.out.println("|          |                               /\\                   |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                0                   |         |");
        System.out.println("|          |                               -|-                  |         |");
        System.out.println("|          |                                |                   |         |");
        System.out.println("|          |                                /\\                  |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                 0                  |         |");
        System.out.println("|          |                                -|-                 |         |");
        System.out.println("|          |                                 |                  |         |");
        System.out.println("|          |                                 /\\                 |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                  0                 |         |");
        System.out.println("|          |                                 -|-                |         |");
        System.out.println("|          |                                  |                 |         |");
        System.out.println("|          |                                  /\\                |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                   0                |         |");
        System.out.println("|          |                                  -|-               |         |");
        System.out.println("|          |                                   |                |         |");
        System.out.println("|          |                                   /\\               |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                    0               |         |");
        System.out.println("|          |                                   -|-              |         |");
        System.out.println("|          |                                    |               |         |");
        System.out.println("|          |                                    /\\              |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                     0              |         |");
        System.out.println("|          |                                    -|-             |         |");
        System.out.println("|          |                                     |              |         |");
        System.out.println("|          |                                     /\\             |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                      0             |         |");
        System.out.println("|          |                                     -|-            |         |");
        System.out.println("|          |                                      |             |         |");
        System.out.println("|          |                                      /\\            |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                       0            |         |");
        System.out.println("|          |                                      -|-           |         |");
        System.out.println("|          |                                       |            |         |");
        System.out.println("|          |                                       /\\           |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                        0           |         |");
        System.out.println("|          |                                       -|-          |         |");
        System.out.println("|          |                                        |           |         |");
        System.out.println("|          |                                        /\\          |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                         0          |         |");
        System.out.println("|          |                                        -|-         |         |");
        System.out.println("|          |                                         |          |         |");
        System.out.println("|          |                                         /\\         |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                          0         |         |");
        System.out.println("|          |                                         -|-        |         |");
        System.out.println("|          |                                          |         |         |");
        System.out.println("|          |                                          /\\        |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                           0        |         |");
        System.out.println("|          |                                          -|-       |         |");
        System.out.println("|          |                                           |        |         |");
        System.out.println("|          |                                           /\\       |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                             0      |         |");
        System.out.println("|          |                                            -|-     |         |");
        System.out.println("|          |                                             |      |         |");
        System.out.println("|          |                                             /\\     |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                              0     |         |");
        System.out.println("|          |                                             -|-    |         |");
        System.out.println("|          |                                              |     |         |");
        System.out.println("|          |                                              /\\    |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                               0    |         |");
        System.out.println("|          |                                              -|-   |         |");
        System.out.println("|          |                                               |    |         |");
        System.out.println("|          |                                               /\\   |         |");
        Act.wait(20);

        System.out.print('\u000c');
        Gamingcode.title();
        Gamingcode.stats();
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println("                                                                           ");
        System.out.println(Var.leavePlace + "                                                      " + Var.goPlace);
        System.out.println("____________                                                    ___________");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                    |         |");
        System.out.println("|          |                                                0   |         |");
        System.out.println("|          |                                               -|-  |         |");
        System.out.println("|          |                                                |   |         |");
        System.out.println("|          |                                                /\\  |         |");
    }
}